import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { test } from "node:test";
import { parseFrontmatter } from "@earendil-works/pi-coding-agent";

const path = resolve(import.meta.dirname, "../../.pi/skills/maquila/SKILL.md");

test("maquila skill is valid, thin, and routes only through public commands", () => {
  const source = readFileSync(path, "utf8");
  const { frontmatter, body } = parseFrontmatter(source);
  assert.equal(frontmatter.name, "maquila");
  assert.equal(typeof frontmatter.description, "string");
  assert.ok(String(frontmatter.description).includes("Linear issue"));
  assert.ok(body.trim().length > 0);
  assert.ok(body.split("\n").length < 500);
  assert.match(body, /maquila setup --from-scratch/);
  assert.match(body, /hidden TTY prompts/);
  assert.match(body, /gh auth login --web --hostname github\.com/);
  assert.match(body, /maquila setup --agent/);
  assert.match(body, /observer ensure --json/);
  assert.match(body, /observer status --json/);
  assert.match(body, /maquila run start --issue/);
  assert.match(body, /maquila doctor --issue "<issue-id>" --json/);
  assert.match(body, /Continue past doctor only when it exits zero/);
  assert.match(body, /same target/);
  assert.match(body, /maquila intake deploy --target/);
  assert.match(body, /--ttl 24h/);
  assert.match(body, /indefinite controller, omit `--ttl`/);
  assert.match(body, /accepts `m`, `h`, `d`, or `w`/);
  assert.match(body, /maquila intake status --json/);
  assert.match(body, /maquila intake destroy --json/);
  assert.match(body, /assigned `Todo` plus exact `maquila-ready`/);
  assert.match(body, /run status --run-id/);
  assert.match(body, /bounded 30–60 second interval/);
  assert.match(body, /Remove the watcher at every terminal state/);
  assert.match(body, /`status: completed`/);
  assert.match(body, /`cleanup: complete`/);
  assert.match(body, /ready-for-review PR URL/);
  assert.match(body, /at least two validated screenshots/);
  assert.match(body, /UI screenshots are mandatory; video is best effort/);
  assert.match(body, /gh pr edit --help/);
  assert.match(body, /Do not blind-repeat a failed run/);
  assert.doesNotMatch(body, /bun run maquila/);
  assert.doesNotMatch(body, /absolute target Git repository path/);
  assert.doesNotMatch(body, /curl .*exe\.dev|readFile|telemetryPath|destroyVm/);
  assert.match(body, /Never print environment values/);
});
