const result = await Bun.build({
  entrypoints: ["src/observer-app.tsx"],
  target: "browser",
  format: "esm",
  minify: true,
  define: { "process.env.NODE_ENV": '"production"' },
});
if (!result.success) throw new Error("observer bundle failed");
const output = result.outputs[0];
if (!output) throw new Error("observer bundle missing");
const code = await output.text();
const literal = `'${code.replaceAll("\\", "\\\\").replaceAll("'", "\\'").replaceAll("\n", "\\n")}'`;
await Bun.write(
  "src/observer-bundle.generated.ts",
  `// Generated by scripts/build-observer-ui.ts. Do not edit.\nexport const OBSERVER_JS =\n  ${literal};\n`,
);
